name: Mr. Stauffer
favicon: null
layout_spectrum: 0
typography_spectrum: 0.07731267297640443
title: Mr. Stauffer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffb6'
    - '#b19388'
    - '#10171f'
    - '#403c53'
    - '#c7ba90'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
