name: Mr. Stauffer
favicon: null
layout_spectrum: 0
typography_spectrum: 0.07731267297640443
title: Mr. Stauffer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6f7487'
    - '#181d17'
    - '#969ba1'
    - '#d0c7be'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
