name: Mr. Stauffer
favicon: null
layout_spectrum: 0.3916180389933288
typography_spectrum: 0.07731267297640443
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6308413743972778
  lightness: 0.15726567688398063
  saturation: 0.734524647006765
  rhythmicContrast: 0.7876303598750383
purpose: []
